/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Adil Sain
 */
public class Suv extends javax.swing.JFrame {

    /**
     * Creates new form Suv
     */
    public Suv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnGit = new javax.swing.JButton();
        lblArkaPlan = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(840, 590));
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "Audi", "BMW", "Mercedes", "Volvo" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(80, 260, 131, 26);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUV Markası Seçiniz");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 230, 131, 24);

        btnGit.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnGit.setText("GİT");
        btnGit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGitActionPerformed(evt);
            }
        });
        getContentPane().add(btnGit);
        btnGit.setBounds(80, 290, 126, 33);

        lblArkaPlan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Adil Sain\\Desktop\\slider-051.jpg")); // NOI18N
        lblArkaPlan.setText("jLabel2");
        getContentPane().add(lblArkaPlan);
        lblArkaPlan.setBounds(0, 0, 840, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGitActionPerformed
        switch(jComboBox1.getSelectedIndex()){
            case 0 : 
                break;
            case 1 :
                SuvMarkalari.Audi audi = new SuvMarkalari.Audi();
                audi.setVisible(true);
                break;
            case 2 : 
                SuvMarkalari.BMW bmw = new SuvMarkalari.BMW();
                bmw.setVisible(true);
                break;
            case 3 :
                SuvMarkalari.Mercedes mercedes = new SuvMarkalari.Mercedes();
                mercedes.setVisible(true);
                break;
            case 4 : 
                SuvMarkalari.Volvo volvo = new SuvMarkalari.Volvo();
                volvo.setVisible(true);
                break;
                default:
                      
        }
    }//GEN-LAST:event_btnGitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblArkaPlan;
    // End of variables declaration//GEN-END:variables
}
